
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: peliculas
  username: carlos1970
  password: junior2006
  host: localhost
  port: 5432

  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: peliculas_test

#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>

production:
  <<: *default
  database: peliculas_production
  username: peliculas
  password: <%= ENV["PELICULAS_DATABASE_PASSWORD"] %>
